### ISSUE TITLE
When using Mail's send_mail(), from_email must be explicitly set as None when maybe it should default to None

### ISSUE THREAD

**Issue by nickjj** [waynerv/flask-mailman#11]
Hi,

In order to use the `send_mail` convinience function you must explicitly define `from_email` even if you plan to use `None` so that it falls back to using your `MAIL_DEFAULT_SENDER`.

That translates to having to call this:

```py
        mail = Mail()
        mail.send_mail(
            subject="Testing",
            message="Hey",
            html_message="<strong>Hey</strong>",
            recipient_list=["test@example.com"],
            from_email=None
        )
```

If you don't supply `from_email` then Flask-Mailman throws an exception saying it must be defined.

Which makes sense because you have `from_email` defined here: https://github.com/waynerv/flask-mailman/blob/03dd1f008396d344184db6e36856c50fb43487f4/flask_mailman/__init__.py#L63

But maybe this should be changed to `from_mail=None` so that users don't need to supply it when they want to use the default sender. This is how `EmailMultiAlternatives` and your other Email class works.

**Comment by waynerv** [comment]
I think your opinion is reasonable.

Already changed in v0.2.2(For fully compatible with previous version, `recipient_list` also set default `None`).

**Comment by nickjj** [comment]
Wow that was fast, thanks!
