### ISSUE TITLE
The docs often reference EMAIL_* variables but the code uses MAIL_* variables

### ISSUE THREAD

**Issue by nickjj** [waynerv/flask-mailman#14]
Hi,

If you goto https://www.waynerv.com/flask-mailman and CTRL + f for `EMAIL_` you'll find lots of results but the source code references `MAIL_` variables. This could lead to folks setting certain config options that have no effect.

**Comment by waynerv** [comment]
These are obviously reckless typos and I will fix it as soon as possible.
Thank you very much!
