### ISSUE TITLE
Release version 1.0.0

### ISSUE THREAD

**Issue by sr-verde** [waynerv/flask-mailman#33]
Thanks for your work!

According to semver:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

Is there any reason not to publish a version 1.0.0? Or is there any plan when to publish 1.0.0?

Best

**Comment by greyli** [comment]
We will release the 1.0 version soon (next month at the latest). Closing now, thanks!
