### ISSUE TITLE
Please support Non-ASCII mailbox names (RFC 6530)

### ISSUE THREAD

**Issue by toddpratt** [waynerv/flask-mailman#38]
* Flask-Mailman version: 0.3.0
* Python version: 3.8
* Operating System: Windows 11

### Description

I am trying to send to an e-mail address with a multibyte mailbox name.  (See https://stackoverflow.com/questions/52133735/how-do-i-send-email-to-addresses-with-non-ascii-characters-in-python)

The e-mail was sent via SMTP but was rejected because the address was seemingly not encoded properly--maybe because the SMTPUTF8 is not set in mail_options calls to sendmail()

**Comment by greyli** [comment]
Assigned to @jingfelix for CodeKitchen Song of Open Source Sprint 1
