### ISSUE TITLE
Is this project still alive? 

### ISSUE THREAD

**Issue by rimvislt** [waynerv/flask-mailman#45]
Is this project still alive? I can not see any releases in 2022 or 2023. Does it mean that it is dead like Flask-mail?

Can you share project ownership and keys with someone else to support this project? ( I will be happy to take over it and help with releases)

**Comment by rimvislt** [comment]
I cloned flask-mail https://github.com/rimvislt/flask-mail2 and will be working on supporting it.

**Comment by greyli** [comment]
Hi, I will help to maintain this project and release a new version soon.
