### ISSUE TITLE
Missing WHEEL during installation

### ISSUE THREAD

**Issue by loleg** [waynerv/flask-mailman#46]
Trying to install, I get this error:

```
  "There is no item named 'Flask_Mailman-0.3.0.dist-info/WHEEL' in the archive"

  at /opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/zipfile.py:1438 in getinfo
```

* Flask-Mailman version: 0.3.0
* Python version: 3.9

**Comment by baurt** [comment]
I don't think this is an issue with this package. Are you using Poetry 1.4.0? If you are, then it's an issue with https://github.com/pypa/installer/issues/134 and there hasn't been any new releases for `installer`. If you use Poetry 1.3.2, it installs just fine.

**Comment by loleg** [comment]
Thanks for the quick reply, and reminder to check my Poetry versions. The error is produced in GitHub's CI, where I needed to do something like this:

```
- name: Install and configure Poetry
  uses: snok/install-poetry@v1
  with:
    version: 1.3.2
```

From the linked issue, I can't tell if I would be able to lift this workaround anytime soon..

**Comment by greyli** [comment]
Thanks @baurt for the info. Closing now.
