### ISSUE TITLE
mkdocs-material-extensions pulled when installing Flask-Mailman

### ISSUE THREAD

**Issue by ignition42** [waynerv/flask-mailman#52]
Hello, I recently installed **Flask-Mailman**, and I noticed that the `mkdocs-material-extensions` extension gets pulled by `pip install Flask-Mailman`.

Is `mkdocs-material-extensions` a mandatory dependency for Flask-Mailman, or is it an optional one?
If it's optional, what functionality or features provides when used with Flask-Mailman?
It's safe to remove `mkdocs-material-extensions` without affecting the core functionality of Flask-Mailman?

Thank you!

**Comment by greyli** [comment]
Thanks for the report, this has been fixed with https://github.com/waynerv/flask-mailman/pull/47.
