### ISSUE TITLE
Question: It's possible to change smtp config before send the mail?

### ISSUE THREAD

**Issue by ricardo17coelho** [waynerv/flask-mailman#6]
Hi

I want to use 2 or more different SMTP configs and before sending the email, change the smtp config depending on some state.
How can i do this?

**Comment by waynerv** [comment]
You can use `conn = mail.get_connection(**kwargs); mail.send_mail(connection=conn)`, the `kwargs` will directly pass to the SMTP backend class for initialize a new instance.
