### ISSUE TITLE
PyPi package code differs from GitHub

### ISSUE THREAD

**Issue by Mercixor** [waynerv/flask-mailman#77]
* Flask-Mailman version: 1.0.0
* Python version: 3.12
* Operating System: OS Independent (Win10/Ubuntu)

### Description

PyPi Package code differs from source code here on GitHub.
Found problem with using SSL connection. Code deployed by PyPi package is from Tag v0.3.0.
Checked at code from class backends/smtp.py.

### What I Did

msg = EmailMessage(subject="Test", to=["test@test.example.de"])
msg.send()

### Errorlog

ERR File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask_mailman/backends/smtp.py", line 74, in open
ERR self.connection = self.connection_class(self.host, self.port, **connection_params)
ERR ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERR TypeError: SMTP_SSL.__init__() got an unexpected keyword argument 'keyfile'

**Comment by greyli** [comment]
I see, the current master branch is not released yet. I just released [1.1.0](https://github.com/waynerv/flask-mailman/releases/tag/v1.1.0) that fixed this issue.
